### ISSUE TITLE
when I use the follew command, The program reported an error

### ISSUE THREAD

**Issue by syssts** [wchill/ffmpy3#11]
inputs = OrderedDict([(outvideo, None), (outvoice, None)])

        outputs = {output, '-c copy -map 0:v:0 -map 1:a:0'}

        ff = ffmpy3.FFmpeg(
            inputs=inputs,
            outputs=outputs
        )
        print(ff.cmd)
        ff.run()

Traceback (most recent call last):
  File "ts.py", line 211, in <module>
    ff = ffmpy3.FFmpeg(
  File "/home/xie/miniconda3/envs/ai/lib/python3.8/site-packages/ffmpy3.py", line 66, in __init__
    self._cmd += _merge_args_opts(outputs)
  File "/home/xie/miniconda3/envs/ai/lib/python3.8/site-packages/ffmpy3.py", line 317, in _merge_args_opts
    for arg, opt in args_opts_dict.items():
AttributeError: 'set' object has no attribute 'items'

**Comment by busterbeam** [comment]
```python3
AttributeError: 'set' object has no attribute 'items'
```
your using a [`set`](https://docs.python.org/3/tutorial/datastructures.html#sets) not a [`dict`](https://docs.python.org/3/tutorial/datastructures.html#dictionaries). (*the tags have links for more info*)
```python3
outputs = {output, '-c copy -map 0:v:0 -map 1:a:0'}
```
should  be
```python3
outputs = {"output": "-c copy -map 0:v:0 -map 1:a:0"}
```
also this
```python3
inputs = OrderedDict([(outvideo, None), (outvoice, None)])
```
could be
```python3
inputs = {outvideo: None, outvoice: None}
```
